#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CloseButton_Black

#include "Basic.hpp"

#include "CloseButton_Black_classes.hpp"
#include "CloseButton_Black_parameters.hpp"


namespace SDK
{

// Function CloseButton_Black.CloseButton_Black_C.ExecuteUbergraph_CloseButton_Black
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCloseButton_Black_C::ExecuteUbergraph_CloseButton_Black(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CloseButton_Black_C", "ExecuteUbergraph_CloseButton_Black");

	Params::CloseButton_Black_C_ExecuteUbergraph_CloseButton_Black Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CloseButton_Black.CloseButton_Black_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCloseButton_Black_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CloseButton_Black_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CloseButton_Black.CloseButton_Black_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UCloseButton_Black_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CloseButton_Black_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CloseButton_Black.CloseButton_Black_C.HandleSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UCloseButton_Black_C::HandleSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CloseButton_Black_C", "HandleSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CloseButton_Black.CloseButton_Black_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UCloseButton_Black_C::SetText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CloseButton_Black_C", "SetText");

	Params::CloseButton_Black_C_SetText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}

}

