#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Calendar_Knockback

#include "Basic.hpp"

#include "GA_Calendar_Knockback_classes.hpp"
#include "GA_Calendar_Knockback_parameters.hpp"


namespace SDK
{

// Function GA_Calendar_Knockback.GA_Calendar_Knockback_C.ExecuteUbergraph_GA_Calendar_Knockback
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Calendar_Knockback_C::ExecuteUbergraph_GA_Calendar_Knockback(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Calendar_Knockback_C", "ExecuteUbergraph_GA_Calendar_Knockback");

	Params::GA_Calendar_Knockback_C_ExecuteUbergraph_GA_Calendar_Knockback Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Calendar_Knockback.GA_Calendar_Knockback_C.DebugWaterwallGameplay
// (BlueprintCallable, BlueprintEvent)

void UGA_Calendar_Knockback_C::DebugWaterwallGameplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Calendar_Knockback_C", "DebugWaterwallGameplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Calendar_Knockback.GA_Calendar_Knockback_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Calendar_Knockback_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Calendar_Knockback_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Calendar_Knockback.GA_Calendar_Knockback_C.OnReady_7389022C4081C8C3936ED1A2932BC0BC
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Calendar_Knockback_C::OnReady_7389022C4081C8C3936ED1A2932BC0BC(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Calendar_Knockback_C", "OnReady_7389022C4081C8C3936ED1A2932BC0BC");

	Params::GA_Calendar_Knockback_C_OnReady_7389022C4081C8C3936ED1A2932BC0BC Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}

}

