#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Special_Knockback

#include "Basic.hpp"

#include "GA_Special_Knockback_classes.hpp"
#include "GA_Special_Knockback_parameters.hpp"


namespace SDK
{

// Function GA_Special_Knockback.GA_Special_Knockback_C.ExecuteUbergraph_GA_Special_Knockback
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Special_Knockback_C::ExecuteUbergraph_GA_Special_Knockback(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "ExecuteUbergraph_GA_Special_Knockback");

	Params::GA_Special_Knockback_C_ExecuteUbergraph_GA_Special_Knockback Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.ResetAboveWaterCall
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::ResetAboveWaterCall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "ResetAboveWaterCall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.DestroyWhatIHit
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UGA_Special_Knockback_C::DestroyWhatIHit(class AActor* SelfActor, class AActor* OtherActor, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "DestroyWhatIHit");

	Params::GA_Special_Knockback_C_DestroyWhatIHit Parms{};

	Parms.SelfActor = SelfActor;
	Parms.OtherActor = OtherActor;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Special_Knockback_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.InWater
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::InWater()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "InWater");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.CheckHeight
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::CheckHeight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "CheckHeight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.ConstantPush
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::ConstantPush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "ConstantPush");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.OnFinish_A91F2F0B40E322CCD07212B0ADA8CCB0
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::OnFinish_A91F2F0B40E322CCD07212B0ADA8CCB0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "OnFinish_A91F2F0B40E322CCD07212B0ADA8CCB0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.Removed_55D484A2481D6216E67737978D39B7BB
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::Removed_55D484A2481D6216E67737978D39B7BB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "Removed_55D484A2481D6216E67737978D39B7BB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.Added_93B708CF46D1927FC9D4BA82EAE52D19
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::Added_93B708CF46D1927FC9D4BA82EAE52D19()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "Added_93B708CF46D1927FC9D4BA82EAE52D19");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.OnReady_5BF758434AA06130F0C122BF8CB8A0D0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Special_Knockback_C::OnReady_5BF758434AA06130F0C122BF8CB8A0D0(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "OnReady_5BF758434AA06130F0C122BF8CB8A0D0");

	Params::GA_Special_Knockback_C_OnReady_5BF758434AA06130F0C122BF8CB8A0D0 Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.Added_AFDBC0BD4FCBD88B771C2CA3D6243E52
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::Added_AFDBC0BD4FCBD88B771C2CA3D6243E52()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "Added_AFDBC0BD4FCBD88B771C2CA3D6243E52");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.Removed_125FBECB482A379477D5758919416F9F
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::Removed_125FBECB482A379477D5758919416F9F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "Removed_125FBECB482A379477D5758919416F9F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.Added_AD5740264D75008832E5AC8163D844EE
// (BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::Added_AD5740264D75008832E5AC8163D844EE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "Added_AD5740264D75008832E5AC8163D844EE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Special_Knockback.GA_Special_Knockback_C.CheckPlayerHeight
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_Special_Knockback_C::CheckPlayerHeight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Special_Knockback_C", "CheckPlayerHeight");

	UObject::ProcessEvent(Func, nullptr);
}

}

