#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Special_Water

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_Special_Water.GCNL_Special_Water_C
// 0x0000 (0x0788 - 0x0788)
class AGCNL_Special_Water_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_Special_Water_C">();
	}
	static class AGCNL_Special_Water_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Special_Water_C>();
	}
};
static_assert(alignof(AGCNL_Special_Water_C) == 0x000008, "Wrong alignment on AGCNL_Special_Water_C");
static_assert(sizeof(AGCNL_Special_Water_C) == 0x000788, "Wrong size on AGCNL_Special_Water_C");

}

