#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IntelCarryObject

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function IntelCarryObject.IntelCarryObject_C.ExecuteUbergraph_IntelCarryObject
// 0x0560 (0x0560 - 0x0000)
struct IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Get_Is_Local_Player_Attacking_is_Attacking; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0048(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_1;                              // 0x0050(0x0018)()
	class FText                                   Temp_text_Variable_2;                              // 0x0068(0x0018)()
	bool                                          Temp_bool_Variable_2;                              // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x0088(0x0018)()
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A3[0x5];                                       // 0x00A3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_3;                              // 0x00A8(0x0018)()
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        CallFunc_GetInstigator_ReturnValue;                // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAbilitySystemComponent*            CallFunc_GetFortAbilitySystemComponent_ReturnValue; // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            CallFunc_BP_FortApplyGameplayEffectToSelf_ReturnValue; // 0x00D8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_4;                              // 0x00E0(0x0018)()
	class AFortPlayerPawn*                        CallFunc_GetInstigator_ReturnValue_1;              // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortAbilitySystemComponent*            CallFunc_GetFortAbilitySystemComponent_ReturnValue_1; // 0x0108(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_5;                              // 0x0110(0x0018)()
	bool                                          Temp_bool_Variable_4;                              // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x012C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0140(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_6;                              // 0x0148(0x0018)()
	class FText                                   Temp_text_Variable_7;                              // 0x0160(0x0018)()
	EIntelStateEnum                               K2Node_CustomEvent_CurrentState;                   // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x3];                                      // 0x0179(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EIntelStateEnum CurrentState)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x017C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_5;                              // 0x018D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18E[0x2];                                      // 0x018E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_8;                              // 0x0190(0x0018)()
	class FText                                   Temp_text_Variable_9;                              // 0x01A8(0x0018)()
	bool                                          Temp_bool_Variable_6;                              // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C1[0x3];                                      // 0x01C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_RemoveActiveEffectsWithTags_ReturnValue;  // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue;          // 0x01D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHUD_InteractionPoint_C*                K2Node_DynamicCast_AsHUD_Interaction_Point;        // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerControllerAthena*            K2Node_DynamicCast_AsFort_Player_Controller_Athena; // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerController*                  K2Node_DynamicCast_AsFort_Player_Controller;       // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_209[0x7];                                      // 0x0209(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        CallFunc_GetPlayerPawn_ReturnValue;                // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0218(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_224[0x4];                                      // 0x0224(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue_1;        // 0x0228(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue_2;        // 0x0230(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UHUD_InteractionPoint_C*                K2Node_DynamicCast_AsHUD_Interaction_Point_1;      // 0x0238(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0241(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_242[0x6];                                      // 0x0242(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerController*                  K2Node_DynamicCast_AsFort_Player_Controller_1;     // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_NewTimeRemaining;               // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x026C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_26D[0x3];                                      // 0x026D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0270(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_DistanceBetweenTwoVectors_Distance;       // 0x027C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(float NewTimeRemaining)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x0280(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_GetGroundTimeRemaining_ReturnValue;       // 0x0290(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0294(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_295[0x3];                                      // 0x0295(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0298(0x0018)()
	class FText                                   Temp_text_Variable_10;                             // 0x02B0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x02C8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0308(0x0010)(ZeroConstructor, ReferenceParm)
	class FText                                   Temp_text_Variable_11;                             // 0x0318(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0330(0x0018)()
	class FText                                   Temp_text_Variable_12;                             // 0x0348(0x0018)()
	class FText                                   Temp_text_Variable_13;                             // 0x0360(0x0018)()
	EIntelStateEnum                               Temp_byte_Variable;                                // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_14;                             // 0x0380(0x0018)()
	bool                                          CallFunc_IsBeingHeldByLocalPlayer_ReturnValue;     // 0x0398(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_7;                              // 0x0399(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bIsClamped;                     // 0x039A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39B[0x5];                                      // 0x039B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_1;                           // 0x03A0(0x0018)()
	TDelegate<void(bool bIsClamped)>              K2Node_CreateDelegate_OutputDelegate_5;            // 0x03B8(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x03C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_1; // 0x03C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_2; // 0x03CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3CB[0x5];                                      // 0x03CB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_2;                           // 0x03D0(0x0018)()
	class FText                                   K2Node_Select_Default_3;                           // 0x03E8(0x0018)()
	class FText                                   K2Node_Select_Default_4;                           // 0x0400(0x0018)()
	class FText                                   K2Node_Select_Default_5;                           // 0x0418(0x0018)()
	bool                                          CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_3; // 0x0430(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_431[0x7];                                      // 0x0431(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default_6;                           // 0x0438(0x0018)()
	struct FSlateBrush                            K2Node_Select_Default_7;                           // 0x0450(0x0088)()
	struct FSlateBrush                            K2Node_Select_Default_8;                           // 0x04D8(0x0088)()
};
static_assert(alignof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject) == 0x000008, "Wrong alignment on IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject");
static_assert(sizeof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject) == 0x000560, "Wrong size on IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, EntryPoint) == 0x000000, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::EntryPoint' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Get_Is_Local_Player_Attacking_is_Attacking) == 0x000004, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Get_Is_Local_Player_Attacking_is_Attacking' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable) == 0x000008, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable) == 0x000020, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate) == 0x000024, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate_1) == 0x000034, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_1) == 0x000044, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000048, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_1) == 0x000050, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_2) == 0x000068, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_2) == 0x000080, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default) == 0x000088, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_IsClosed_Variable) == 0x0000A0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_3) == 0x0000A1, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_HasAuthority_ReturnValue) == 0x0000A2, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_3) == 0x0000A8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_HasAuthority_ReturnValue_1) == 0x0000C0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_HasAuthority_ReturnValue_2) == 0x0000C1, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetInstigator_ReturnValue) == 0x0000C8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetFortAbilitySystemComponent_ReturnValue) == 0x0000D0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetFortAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_BP_FortApplyGameplayEffectToSelf_ReturnValue) == 0x0000D8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_BP_FortApplyGameplayEffectToSelf_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_4) == 0x0000E0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_4' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetInstigator_ReturnValue_1) == 0x0000F8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_IsValid_ReturnValue) == 0x000100, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetFortAbilitySystemComponent_ReturnValue_1) == 0x000108, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetFortAbilitySystemComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_5) == 0x000110, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_5' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_4) == 0x000128, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate_2) == 0x00012C, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000140, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_6) == 0x000148, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_6' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_7) == 0x000160, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_7' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CustomEvent_CurrentState) == 0x000178, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CustomEvent_CurrentState' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate_3) == 0x00017C, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00018C, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_5) == 0x00018D, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_8) == 0x000190, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_8' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_9) == 0x0001A8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_9' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_6) == 0x0001C0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_RemoveActiveEffectsWithTags_ReturnValue) == 0x0001C4, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_RemoveActiveEffectsWithTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_IsValid_ReturnValue_1) == 0x0001C8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetUserWidgetObject_ReturnValue) == 0x0001D0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetUserWidgetObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetOwningPlayer_ReturnValue) == 0x0001D8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_AsHUD_Interaction_Point) == 0x0001E0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_AsHUD_Interaction_Point' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_bSuccess) == 0x0001E8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_AsFort_Player_Controller_Athena) == 0x0001F0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_bSuccess_1) == 0x0001F8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_AsFort_Player_Controller) == 0x000200, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_AsFort_Player_Controller' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_bSuccess_2) == 0x000208, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetPlayerPawn_ReturnValue) == 0x000210, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000218, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetUserWidgetObject_ReturnValue_1) == 0x000228, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetUserWidgetObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetUserWidgetObject_ReturnValue_2) == 0x000230, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetUserWidgetObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_AsHUD_Interaction_Point_1) == 0x000238, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_AsHUD_Interaction_Point_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_bSuccess_3) == 0x000240, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_IsValid_ReturnValue_2) == 0x000241, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetOwningPlayer_ReturnValue_1) == 0x000248, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetOwningPlayer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_AsFort_Player_Controller_1) == 0x000250, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_AsFort_Player_Controller_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_DynamicCast_bSuccess_4) == 0x000258, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x000260, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CustomEvent_NewTimeRemaining) == 0x000268, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CustomEvent_NewTimeRemaining' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_IsValid_ReturnValue_3) == 0x00026C, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000270, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_DistanceBetweenTwoVectors_Distance) == 0x00027C, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_DistanceBetweenTwoVectors_Distance' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate_4) == 0x000280, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_GetGroundTimeRemaining_ReturnValue) == 0x000290, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_GetGroundTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000294, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Conv_FloatToText_ReturnValue) == 0x000298, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_10) == 0x0002B0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_10' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_MakeStruct_FormatArgumentData) == 0x0002C8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_MakeArray_Array) == 0x000308, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_11) == 0x000318, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_11' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Format_ReturnValue) == 0x000330, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_12) == 0x000348, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_12' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_13) == 0x000360, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_13' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_byte_Variable) == 0x000378, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_text_Variable_14) == 0x000380, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_text_Variable_14' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_IsBeingHeldByLocalPlayer_ReturnValue) == 0x000398, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_IsBeingHeldByLocalPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Variable_7) == 0x000399, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CustomEvent_bIsClamped) == 0x00039A, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CustomEvent_bIsClamped' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_1) == 0x0003A0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_CreateDelegate_OutputDelegate_5) == 0x0003B8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, Temp_bool_Has_Been_Initd_Variable) == 0x0003C8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_1) == 0x0003C9, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_2) == 0x0003CA, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_2) == 0x0003D0, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_3) == 0x0003E8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_4) == 0x000400, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_5) == 0x000418, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_3) == 0x000430, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::CallFunc_Get_Is_Local_Player_Attacking_is_Attacking_3' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_6) == 0x000438, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_6' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_7) == 0x000450, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_7' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject, K2Node_Select_Default_8) == 0x0004D8, "Member 'IntelCarryObject_C_ExecuteUbergraph_IntelCarryObject::K2Node_Select_Default_8' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.InteractionPointClamped
// 0x0001 (0x0001 - 0x0000)
struct IntelCarryObject_C_InteractionPointClamped final
{
public:
	bool                                          bIsClamped;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(IntelCarryObject_C_InteractionPointClamped) == 0x000001, "Wrong alignment on IntelCarryObject_C_InteractionPointClamped");
static_assert(sizeof(IntelCarryObject_C_InteractionPointClamped) == 0x000001, "Wrong size on IntelCarryObject_C_InteractionPointClamped");
static_assert(offsetof(IntelCarryObject_C_InteractionPointClamped, bIsClamped) == 0x000000, "Member 'IntelCarryObject_C_InteractionPointClamped::bIsClamped' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.EventStartDropTimer
// 0x0004 (0x0004 - 0x0000)
struct IntelCarryObject_C_EventStartDropTimer final
{
public:
	float                                         NewTimeRemaining;                                  // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IntelCarryObject_C_EventStartDropTimer) == 0x000004, "Wrong alignment on IntelCarryObject_C_EventStartDropTimer");
static_assert(sizeof(IntelCarryObject_C_EventStartDropTimer) == 0x000004, "Wrong size on IntelCarryObject_C_EventStartDropTimer");
static_assert(offsetof(IntelCarryObject_C_EventStartDropTimer, NewTimeRemaining) == 0x000000, "Member 'IntelCarryObject_C_EventStartDropTimer::NewTimeRemaining' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.IntelStateChanged
// 0x0001 (0x0001 - 0x0000)
struct IntelCarryObject_C_IntelStateChanged final
{
public:
	EIntelStateEnum                               CurrentState;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IntelCarryObject_C_IntelStateChanged) == 0x000001, "Wrong alignment on IntelCarryObject_C_IntelStateChanged");
static_assert(sizeof(IntelCarryObject_C_IntelStateChanged) == 0x000001, "Wrong size on IntelCarryObject_C_IntelStateChanged");
static_assert(offsetof(IntelCarryObject_C_IntelStateChanged, CurrentState) == 0x000000, "Member 'IntelCarryObject_C_IntelStateChanged::CurrentState' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.Set UIVisibility
// 0x0038 (0x0038 - 0x0000)
struct IntelCarryObject_C_Set_UIVisibility final
{
public:
	float                                         PlayerDistance;                                    // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetComponent*                       UITarget;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UHUD_InteractionPoint_C*                K2Node_DynamicCast_AsHUD_Interaction_Point;        // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_1;            // 0x0033(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Select_Default;                             // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(IntelCarryObject_C_Set_UIVisibility) == 0x000008, "Wrong alignment on IntelCarryObject_C_Set_UIVisibility");
static_assert(sizeof(IntelCarryObject_C_Set_UIVisibility) == 0x000038, "Wrong size on IntelCarryObject_C_Set_UIVisibility");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, PlayerDistance) == 0x000000, "Member 'IntelCarryObject_C_Set_UIVisibility::PlayerDistance' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, UITarget) == 0x000008, "Member 'IntelCarryObject_C_Set_UIVisibility::UITarget' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, Temp_bool_Variable) == 0x000010, "Member 'IntelCarryObject_C_Set_UIVisibility::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, CallFunc_Not_PreBool_ReturnValue) == 0x000011, "Member 'IntelCarryObject_C_Set_UIVisibility::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, CallFunc_GetUserWidgetObject_ReturnValue) == 0x000018, "Member 'IntelCarryObject_C_Set_UIVisibility::CallFunc_GetUserWidgetObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, Temp_bool_Variable_1) == 0x000020, "Member 'IntelCarryObject_C_Set_UIVisibility::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, K2Node_DynamicCast_AsHUD_Interaction_Point) == 0x000028, "Member 'IntelCarryObject_C_Set_UIVisibility::K2Node_DynamicCast_AsHUD_Interaction_Point' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'IntelCarryObject_C_Set_UIVisibility::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, Temp_bool_Variable_2) == 0x000031, "Member 'IntelCarryObject_C_Set_UIVisibility::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, CallFunc_Less_FloatFloat_ReturnValue) == 0x000032, "Member 'IntelCarryObject_C_Set_UIVisibility::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, CallFunc_Less_FloatFloat_ReturnValue_1) == 0x000033, "Member 'IntelCarryObject_C_Set_UIVisibility::CallFunc_Less_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Set_UIVisibility, K2Node_Select_Default) == 0x000034, "Member 'IntelCarryObject_C_Set_UIVisibility::K2Node_Select_Default' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.OnRep_IsPickedUp
// 0x0010 (0x0010 - 0x0000)
struct IntelCarryObject_C_OnRep_IsPickedUp final
{
public:
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent*                     CallFunc_SpawnFXSystemAttached_ReturnValue;        // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(IntelCarryObject_C_OnRep_IsPickedUp) == 0x000008, "Wrong alignment on IntelCarryObject_C_OnRep_IsPickedUp");
static_assert(sizeof(IntelCarryObject_C_OnRep_IsPickedUp) == 0x000010, "Wrong size on IntelCarryObject_C_OnRep_IsPickedUp");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPickedUp, CallFunc_HasAuthority_ReturnValue) == 0x000000, "Member 'IntelCarryObject_C_OnRep_IsPickedUp::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPickedUp, CallFunc_SpawnFXSystemAttached_ReturnValue) == 0x000008, "Member 'IntelCarryObject_C_OnRep_IsPickedUp::CallFunc_SpawnFXSystemAttached_ReturnValue' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.OnRep_IsPlaced
// 0x0150 (0x0150 - 0x0000)
struct IntelCarryObject_C_OnRep_IsPlaced final
{
public:
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0xF];                                        // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0010(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0040(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemComponent*                     CallFunc_SpawnFXAtLocation_ReturnValue;            // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0078(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0xC];                                       // 0x0084(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0090(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x00C0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(IntelCarryObject_C_OnRep_IsPlaced) == 0x000010, "Wrong alignment on IntelCarryObject_C_OnRep_IsPlaced");
static_assert(sizeof(IntelCarryObject_C_OnRep_IsPlaced) == 0x000150, "Wrong size on IntelCarryObject_C_OnRep_IsPlaced");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_HasAuthority_ReturnValue) == 0x000000, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000010, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000040, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_BreakTransform_Location) == 0x00004C, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_BreakTransform_Rotation) == 0x000058, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_BreakTransform_Scale) == 0x000064, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_SpawnFXAtLocation_ReturnValue) == 0x000070, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_SpawnFXAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_Add_VectorVector_ReturnValue) == 0x000078, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_MakeTransform_ReturnValue) == 0x000090, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_OnRep_IsPlaced, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x0000C0, "Member 'IntelCarryObject_C_OnRep_IsPlaced::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.Get Is Local Player Attacking
// 0x0020 (0x0020 - 0x0000)
struct IntelCarryObject_C_Get_Is_Local_Player_Attacking final
{
public:
	bool                                          Is_Attacking;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerControllerAthena*            K2Node_DynamicCast_AsFort_Player_Controller_Athena; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocalPlayerAttacking_ReturnValue;       // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(IntelCarryObject_C_Get_Is_Local_Player_Attacking) == 0x000008, "Wrong alignment on IntelCarryObject_C_Get_Is_Local_Player_Attacking");
static_assert(sizeof(IntelCarryObject_C_Get_Is_Local_Player_Attacking) == 0x000020, "Wrong size on IntelCarryObject_C_Get_Is_Local_Player_Attacking");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, Is_Attacking) == 0x000000, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::Is_Attacking' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, CallFunc_HasAuthority_ReturnValue) == 0x000001, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, CallFunc_IsValid_ReturnValue) == 0x000002, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, K2Node_DynamicCast_AsFort_Player_Controller_Athena) == 0x000010, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::K2Node_DynamicCast_AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_Get_Is_Local_Player_Attacking, CallFunc_IsLocalPlayerAttacking_ReturnValue) == 0x000019, "Member 'IntelCarryObject_C_Get_Is_Local_Player_Attacking::CallFunc_IsLocalPlayerAttacking_ReturnValue' has a wrong offset!");

// Function IntelCarryObject.IntelCarryObject_C.BlueprintCanInteract
// 0x0160 (0x0160 - 0x0000)
struct IntelCarryObject_C_BlueprintCanInteract final
{
public:
	const class AFortPawn*                        InteractingPawn;                                   // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInteractionBeingAttempted                    InteractionBeingAttempted;                         // 0x0008(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETInteractionType                             InteractionType;                                   // 0x0009(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x000A(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          IsHitActorBlockingInteract;                        // 0x000B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetAttackingTeam_ReturnValue;             // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetActorTeam_ReturnValue;                 // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BlueprintCanInteract_ReturnValue;         // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F[0x1];                                       // 0x002F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x003C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetAttackingTeam_ReturnValue_1;           // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x00CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x00CB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakHitResult_Time;                      // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x00D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x00E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x00EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x00F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0118(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0130(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x013C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerPawn_Athena_C*                   K2Node_DynamicCast_AsPlayer_Pawn_Athena;           // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetActorTeam_ReturnValue_1;               // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x015A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x015B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x015D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(IntelCarryObject_C_BlueprintCanInteract) == 0x000008, "Wrong alignment on IntelCarryObject_C_BlueprintCanInteract");
static_assert(sizeof(IntelCarryObject_C_BlueprintCanInteract) == 0x000160, "Wrong size on IntelCarryObject_C_BlueprintCanInteract");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, InteractingPawn) == 0x000000, "Member 'IntelCarryObject_C_BlueprintCanInteract::InteractingPawn' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, InteractionBeingAttempted) == 0x000008, "Member 'IntelCarryObject_C_BlueprintCanInteract::InteractionBeingAttempted' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, InteractionType) == 0x000009, "Member 'IntelCarryObject_C_BlueprintCanInteract::InteractionType' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, ReturnValue) == 0x00000A, "Member 'IntelCarryObject_C_BlueprintCanInteract::ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, IsHitActorBlockingInteract) == 0x00000B, "Member 'IntelCarryObject_C_BlueprintCanInteract::IsHitActorBlockingInteract' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_GetAttackingTeam_ReturnValue) == 0x00000C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_GetAttackingTeam_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, K2Node_MakeArray_Array) == 0x000010, "Member 'IntelCarryObject_C_BlueprintCanInteract::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000020, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_Not_PreBool_ReturnValue) == 0x00002C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_GetActorTeam_ReturnValue) == 0x00002D, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_GetActorTeam_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BlueprintCanInteract_ReturnValue) == 0x00002E, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BlueprintCanInteract_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000030, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_LineTraceSingle_OutHit) == 0x00003C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_LineTraceSingle_ReturnValue) == 0x0000C8, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_GetAttackingTeam_ReturnValue_1) == 0x0000C9, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_GetAttackingTeam_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_bBlockingHit) == 0x0000CA, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_bInitialOverlap) == 0x0000CB, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_Time) == 0x0000CC, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_Distance) == 0x0000D0, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_Location) == 0x0000D4, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_ImpactPoint) == 0x0000E0, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_Normal) == 0x0000EC, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_ImpactNormal) == 0x0000F8, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_PhysMat) == 0x000108, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_HitActor) == 0x000110, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_HitComponent) == 0x000118, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_HitBoneName) == 0x000120, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_HitItem) == 0x000128, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_FaceIndex) == 0x00012C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_TraceStart) == 0x000130, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BreakHitResult_TraceEnd) == 0x00013C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000148, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, K2Node_DynamicCast_AsPlayer_Pawn_Athena) == 0x000150, "Member 'IntelCarryObject_C_BlueprintCanInteract::K2Node_DynamicCast_AsPlayer_Pawn_Athena' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, K2Node_DynamicCast_bSuccess) == 0x000158, "Member 'IntelCarryObject_C_BlueprintCanInteract::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_GetActorTeam_ReturnValue_1) == 0x000159, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_GetActorTeam_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x00015A, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BooleanAND_ReturnValue) == 0x00015B, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BooleanAND_ReturnValue_1) == 0x00015C, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(IntelCarryObject_C_BlueprintCanInteract, CallFunc_BooleanAND_ReturnValue_2) == 0x00015D, "Member 'IntelCarryObject_C_BlueprintCanInteract::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");

}

