#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayspaceFramework

#include "Basic.hpp"

#include "PlayspaceFramework_structs.hpp"


namespace SDK::Params
{

// Function PlayspaceFramework.PlayspaceControllerComponent_PlayerSpawning.GetSpawnInfo
// 0x001C (0x001C - 0x0000)
struct PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo final
{
public:
	struct FReplicatedSpawnInfo                   ReturnValue;                                       // 0x0000(0x001C)(ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo) == 0x000004, "Wrong alignment on PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo");
static_assert(sizeof(PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo) == 0x00001C, "Wrong size on PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo");
static_assert(offsetof(PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo, ReturnValue) == 0x000000, "Member 'PlayspaceControllerComponent_PlayerSpawning_GetSpawnInfo::ReturnValue' has a wrong offset!");

}

