#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpatialMapPreviewScreen

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SpatialMapPreviewScreen.SpatialMapPreviewScreen_C
// 0x0000 (0x0508 - 0x0508)
class USpatialMapPreviewScreen_C final : public USpatialMapPreviewScreen
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpatialMapPreviewScreen_C">();
	}
	static class USpatialMapPreviewScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpatialMapPreviewScreen_C>();
	}
};
static_assert(alignof(USpatialMapPreviewScreen_C) == 0x000008, "Wrong alignment on USpatialMapPreviewScreen_C");
static_assert(sizeof(USpatialMapPreviewScreen_C) == 0x000508, "Wrong size on USpatialMapPreviewScreen_C");

}

