#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M_MED_Galileo_Gondola_AnimBp

#include "Basic.hpp"

#include "M_MED_Galileo_Gondola_AnimBp_classes.hpp"
#include "M_MED_Galileo_Gondola_AnimBp_parameters.hpp"


namespace SDK
{

// Function M_MED_Galileo_Gondola_AnimBp.M_MED_Galileo_Gondola_AnimBp_C.ExecuteUbergraph_M_MED_Galileo_Gondola_AnimBp
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UM_MED_Galileo_Gondola_AnimBp_C::ExecuteUbergraph_M_MED_Galileo_Gondola_AnimBp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("M_MED_Galileo_Gondola_AnimBp_C", "ExecuteUbergraph_M_MED_Galileo_Gondola_AnimBp");

	Params::M_MED_Galileo_Gondola_AnimBp_C_ExecuteUbergraph_M_MED_Galileo_Gondola_AnimBp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function M_MED_Galileo_Gondola_AnimBp.M_MED_Galileo_Gondola_AnimBp_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UM_MED_Galileo_Gondola_AnimBp_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("M_MED_Galileo_Gondola_AnimBp_C", "BlueprintUpdateAnimation");

	Params::M_MED_Galileo_Gondola_AnimBp_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function M_MED_Galileo_Gondola_AnimBp.M_MED_Galileo_Gondola_AnimBp_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UM_MED_Galileo_Gondola_AnimBp_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("M_MED_Galileo_Gondola_AnimBp_C", "AnimGraph");

	Params::M_MED_Galileo_Gondola_AnimBp_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

